spring:
  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
        defaultZone: ${EUREKA_URL:http://appeureka:8761/eureka}
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  