spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
# User Service Routes
            - id: read_user
              uri: http://localhost:8181
              predicates:
                - Path=/api/users/read/id/{id:[0-9]+}
                - Method=GET

            - id: create_user
              uri: http://localhost:8181
              predicates:
                - Path=/api/users/create
                - Method=PUT

            - id: update_user
              uri: http://localhost:8181
              predicates:
                - Path=/api/users/update/old-id/{id:[0-9]+}
                - Method=PUT

            - id: delete_user
              uri: http://localhost:8181
              predicates:
                - Path=/api/users/delete/id/{id:[0-9]+}
                - Method=DELETE

            - id: read_all_users
              uri: http://localhost:8181
              predicates:
                - Path=/api/users/findAll
                - Method=GET
  # Mail Service Routes
            - id: notify_by_email_add_user
              uri: http://localhost:8282
              predicates:
                - Path=/api/mail/sendAdd/{mail}
                - Method=GET

            - id: notify_by_email_remove_user
              uri: http://localhost:8282
              predicates:
                - Path=/api/mail/sendRemove/{mail}
                - Method=GET