spring:
  mail:
    username: ${MAIL_NAME}
    password: ${MAIL_PASSWORD}
    host: smtp.yandex.ru
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

    debug: true

  kafka:
    bootstrap-servers: ${KAFKA_URL:http://localhost:19092}
    consumer:
      auto-offset-reset: earliest
      group-id: example123
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1
      fetch-max-wait: 36000
      enable-auto-commit: false
      client-id: example
    listener:
      poll-timeout: 5000
      concurrency: 1
      ack-mode: manual_immediate

  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL:http://appeureka:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Разрешить все endpoints
      base-path: /actuator  # Базовый путь
  endpoint:
    env:
      enabled: true  # Явно включить env endpoint
      show-values: ALWAYS
    health:
      enabled: true
    info:
      enabled: true