spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://172.18.0.2:5432/postgres}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        cache:
          use_second_level_cache: false
        connection:
          pool_size: 10
          autocommit: false
        current_session_context_class: thread
  kafka:
    bootstrap-servers: 172.18.0.4:19092
    producer:
      client-id: example
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 2

  eureka:
    client:
      serviceUrl:
        defaultZone: http://172.18.0.6:8761/eureka/

  resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            failureRateThreshold: 50
            waitDurationInOpenState: 5s

  resilience4j.timelimiter:
      configs:
          default:
              timeoutDuration: 5s
              cancelRunningFuture: true